### PR TITLE
add provider: israbike

### PR DESCRIPTION
**Pull request by ohadcn**
Israbike is a dockless bike rental service in Israel (Tel Aviv & Netanya).

Those changes should make Israbike bikes visible in multicycle.

REVIEW NEEDED:
- Since I'm new to the project, I haven't run the full code on my machine (haven't installed postgresql and created google app for it), so further review might be needed.
- someone with prior graphics knowledge might use a better compression for the graphics files to make them smaller and the all app healthier.

### CODE REVIEW

**Comment by PierrickP** [comment]
hello,

THANKS !
It was on my sharingos' todo list.

Merged with 25b032e5d5375de725b8fb043954ba402ce9992f fixes

Do you know some other systems available in Tel-Aviv ?

**Comment by PierrickP** [comment]
Do you have a twitter account ?

**Comment by ohadcn** [comment]
@PierrickP 
A. My Twitter username is the same as my github username, you can find me there.
B. Other bike systems in TLV are already in multicycle (telofan and few international providers - like mobike, wind and lime)
C. We might add car rental services which are missing (Autotel, Car2go)
D. Israbike bikes are now marked on multicycle in green, which might looks confusing with lime scooters (both works in TLV)
I tried to use a blue marker (the same color as Israbike logo and bikes)

**Comment by ohadcn** [comment]
Thanks

**Comment by PierrickP** [comment]
A. 👍 
B / C. https://github.com/PierrickP/multicycles/issues/70 is planned but cars system are not prioritary
D. Refresh or clean cache

**Comment by ohadcn** [comment]
D. Cleaning cache works for me
thanks

**Pull request merged**
