### PR TITLE
ci: always use the latest lts version

### PR DESCRIPTION
**Pull request by douglasduteil**
---

What do you think about always running the latest lts version ?
The current one is `node@10.13.0`

### CODE REVIEW

**Comment by douglasduteil** [comment]
Hum... :thinking: 
Is it normal that PRs trigger the "deploy" stage on Travis ?
Did I publish something on Docker Hub :whale: ?

**Comment by PierrickP** [comment]
If think, this should be more restricted
https://github.com/PierrickP/multicycles/blob/9bba9f8718fd01ec7e92cb5c49bdcc06ef77c158/.travis.yml#L4

Thank for your PR, lts seem better :)

**Comment by PierrickP** [comment]
you pushed nothing, but i don't know why :D

**Comment by PierrickP** [comment]
Ok, rebase on master & remove unrelated changes (package*.json)

**Comment by douglasduteil** [comment]
If I remove the changes on `providers/pony/package*.json` change the tests will not pass (see 88df809 [build result](https://travis-ci.org/PierrickP/multicycles/builds/454845682))
Is that what you want ?

**Pull request closed without merging**
